# Generated by Django 6.0.2 on 2026-03-20 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_assignment_deadline_and_more'),
        ('skills', '0003_alter_skill_options'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='assignment',
            name='positive_effort_estimate',
        ),
        migrations.AddField(
            model_name='project',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='projects', to='skills.skill'),
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='effort_estimate',
        ),
    ]
