# Generated by Django 6.0.2 on 2026-03-20 11:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_assignment_positive_effort_estimate_and_more'),
        ('skills', '0004_skill_notes_alter_skill_depth_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='assignment',
            name='projects_as_complet_c754b1_idx',
        ),
        migrations.AddField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=20),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['status'], name='projects_as_status_7e21b9_idx'),
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='completed',
        ),
    ]
