# Generated by Django 6.0.2 on 2026-03-19 04:54

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_token_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 3, 19, 4, 54, 21, 507306, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
