# Generated by Django 6.0.1 on 2026-02-28 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('week_start', models.DateField()),
                ('top_three_text', models.TextField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Weekly Priority',
                'verbose_name_plural': 'Weekly Priorities',
                'ordering': ['-week_start'],
                'indexes': [models.Index(fields=['owner'], name='planning_we_owner_i_42a733_idx'), models.Index(fields=['week_start'], name='planning_we_week_st_25f503_idx')],
                'constraints': [models.UniqueConstraint(fields=('owner', 'week_start'), name='unique_week_per_user')],
            },
        ),
    ]
