# Generated by Django 6.0.2 on 2026-04-09 00:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
        ('projects', '0005_remove_assignment_projects_as_complet_c754b1_idx_and_more'),
        ('skills', '0004_skill_notes_alter_skill_depth_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklypriority',
            name='top_three_text',
        ),
        migrations.CreateModel(
            name='PriorityItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveSmallIntegerField()),
                ('text', models.CharField(max_length=300)),
                ('is_done', models.BooleanField(default=False)),
                ('linked_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.assignment')),
                ('linked_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project')),
                ('linked_skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='skills.skill')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to=settings.AUTH_USER_MODEL)),
                ('weekly_priority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='planning.weeklypriority')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
