# Generated by Django 6.0.1 on 2026-02-28 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_alter_assignment_options_alter_project_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('problem_statement', models.TextField()),
                ('target_user', models.CharField(max_length=200)),
                ('revenue_model', models.CharField(max_length=200)),
                ('complexity_score', models.PositiveSmallIntegerField()),
                ('status', models.CharField(default='draft', max_length=30)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to=settings.AUTH_USER_MODEL)),
                ('related_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ideas', to='projects.project')),
            ],
            options={
                'verbose_name': 'Idea',
                'verbose_name_plural': 'Ideas',
                'indexes': [models.Index(fields=['status'], name='ideas_idea_status_255711_idx'), models.Index(fields=['complexity_score'], name='ideas_idea_complex_abd25d_idx')],
            },
        ),
    ]
