# Generated by Django 6.0.2 on 2026-04-09 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
        ('skills', '0004_skill_notes_alter_skill_depth_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='related_skills',
            field=models.ManyToManyField(blank=True, related_name='ideas', to='skills.skill'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title',
            field=models.CharField(default='Untitled Idea', max_length=200),
        ),
    ]
