# Generated by Django 6.0.2 on 2026-04-10 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0002_idea_related_skills_idea_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='idea',
            options={'ordering': ['-created_at'], 'verbose_name': 'Idea', 'verbose_name_plural': 'Ideas'},
        ),
    ]
