# Generated by Django 6.0.1 on 2026-02-28 12:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name': 'Skill', 'verbose_name_plural': 'Skills'},
        ),
        migrations.AlterField(
            model_name='skill',
            name='depth_level',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='skill',
            name='last_practiced',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['owner'], name='skills_skil_owner_i_00ea06_idx'),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['last_practiced'], name='skills_skil_last_pr_6164fe_idx'),
        ),
    ]
