# Generated by Django 6.0.2 on 2026-03-12 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_alter_skill_options_alter_skill_depth_level_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['created_at'], 'verbose_name': 'Skill', 'verbose_name_plural': 'Skills'},
        ),
    ]
