# Generated by Django 6.0.2 on 2026-04-25 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(choices=[('idea_created', 'Created an idea'), ('idea_updated', 'Updated an idea'), ('idea_deleted', 'Deleted an idea'), ('idea_converted', 'Converted idea to project'), ('project_created', 'Created a project'), ('project_updated', 'Updated a project'), ('project_deleted', 'Deleted a project'), ('project_completed', 'Completed a project'), ('assignment_created', 'Created an assignment'), ('assignment_completed', 'Completed an assignment'), ('assignment_deleted', 'Deleted an assignment'), ('skill_created', 'Added a skill'), ('skill_practiced', 'Practiced a skill'), ('skill_deleted', 'Deleted a skill'), ('skill_upgraded', 'Upgraded skill level'), ('plan_created', 'Created weekly plan'), ('plan_deleted', 'Deleted weekly plan'), ('item_done', 'Completed a priority item'), ('streak_milestone', 'Hit a streak milestone')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True, default='')),
                ('is_read', models.BooleanField(default=False)),
                ('target_type', models.CharField(blank=True, choices=[('idea', 'Idea'), ('project', 'Project'), ('assignment', 'Assignment'), ('skill', 'Skill'), ('weekly_priority', 'Weekly Priority'), ('priority_item', 'Priority Item'), ('streak', 'Streak')], default='', max_length=20)),
                ('target_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
